require('nvim-treesitter.configs').setup {
    ensure_installed = { 
        'bash',
        'c',
        'cmake',
        'comment',
        'cpp',
        'dockerfile',
        'gitignore',
        'groovy',
        'json',
        'llvm',
        'lua',
        'make',
        'markdown',
        'markdown_inline',
        'meson',
        'ninja',
        'python',
        'query',
        'regex',
        'rust',
        'toml',
        'vim',
        'vimdoc',
        'yaml',
    },
    highlight = {
        enable = true,
    },
    parser_install_dir = '~/.config/nvim/bin/parsers',
}
